### ISSUE TITLE
Can there be a default login workflow for WebApps?

### ISSUE THREAD

**Issue by proffapt** [proffapt/iitkgp-erp-login-pypi#15]
### Idea

A default workflow of login in case of webapps integrated into the currently existing `login()` function.
Currently the workflow for webapps is broken into various steps through functions, basically like below:
<img width="1000" alt="image" src="https://github.com/proffapt/iitkgp-erp-login-pypi/assets/86282911/8596f819-a3bd-4717-a321-874b1845d0d2">

What I want is a one liner to implement all of this from developer's perspective.
Break the workflow in 3-4 endpoints (as to-and-fro data passing is required). Implement those endpoints with proper error handling so that whichever frontend implements them can have proper logs.

### Version

If done it will be `v2.4.0`.

**Comment by Devansh-bit** [comment]
How will this be implemented? 
Since the login flow cannot be completed in a single request due to the question, there needs to be tight integration between the client and the server. A redirect can be built for the oneliner but that takes away the customization for the developer. Am I missing something?

**Comment by proffapt** [comment]
> A redirect can be built for the oneliner

What exactly?

**Comment by Devansh-bit** [comment]
The API endpoint redirects the user to a page from the library, which completes the login and then directs the user back to the main application

**Comment by proffapt** [comment]
hmm, no, that will really take away freedom from the developer

**Comment by Devansh-bit** [comment]
Yeah, so how are we supposed to make it work then?

**Comment by proffapt** [comment]
That's the question XD.. It has a question tag..

**Comment by proffapt** [comment]
Temporarily closing this issue.
- This doesn't fall under the current scope and vision of the project
- This was planned to be just used in "CLI" "python" scripts
- I personally do not build webapps
- Even if i do, that won't surely be in python :)

**Comment by tanush-128** [comment]
I would like to work on it
