### ISSUE TITLE
Session & Credentials management for WebApps

### ISSUE THREAD

**Issue by proffapt** [proffapt/iitkgp-erp-login-pypi#16]
Moving on from the basic iteration of just the workflow, integrating the specialities of CLI workflow into that of webapp will be wonderful.

- [x] sessionToken & ssoToken storage and retrieval

**Comment by onkar-1432** [comment]
Can you please assign me this issue for Kwoc 2023. I will do my best to resolve these issue.

**Comment by onkar-1432** [comment]
@proffapt

**Comment by proffapt** [comment]
Yeah great! Make sure to start "commiting" after 9th December.. as the coding period will start then only.

**Comment by proffapt** [comment]
Temporarily closing this issue.
- This doesn't fall under the current scope and vision of the project
- This was planned to be just used in "CLI" "python" scripts
- I personally do not build webapps
- Even if i do, that won't surely be in python :)
