### ISSUE TITLE
[BUG]: session_valid() is broken

### ISSUE THREAD

**Issue by proffapt** [proffapt/iitkgp-erp-login-pypi#19]
**To Reproduce**
1. Use `open_erp.py`
2. Logout ERP from browser
3. Use `open_erp.py` again

**Expected behavior**
Either say it is valid or say it is not, and if it is something new then handle this case

**Screenshots**
![image](https://github.com/proffapt/iitkgp-erp-login-pypi/assets/86282911/aa94441e-c04f-4c5b-bf6d-5460837f41b7)

**Additional Context**
Even if the `session_valid()` returns `True` in this case, the page says "The session is idle for too long time, re-login".

**Comment by proffapt** [comment]
@shikharish reply so that I can assign it to you.

**Comment by shikharish** [comment]
I will work on this.

**Comment by proffapt** [comment]
resolved in https://github.com/proffapt/iitkgp-erp-login-pypi/releases/tag/v2.3.3
