### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by harshkhandeparkar** [proffapt/iitkgp-erp-login-pypi#3]
**Is your feature request related to a problem? Please describe.**
The package is written in Python. That is a big problem.

**Describe the solution you'd like**
Rewrite in [Rust](https://rust-lang.org)

**Describe alternatives you've considered**
Any language, really.

**Comment by proffapt** [comment]
It's about reach and ease, people who know rust are already rare, and to create a package for them.. doesn't make sense.
Also, legacy codebase is in python.
